### ISSUE TITLE
Format code using latest standards

### ISSUE THREAD

**Issue by johnhaley81** [RationalJS/future#28]
I was wondering why the deprecated fast pipe operator (`|.`) is still being used in the docs and code. Is this to maintain backwards compatibility?

**Comment by scull7** [comment]
There was a PR #26 That fixed this for some of the documentation.  I don't believe there is a reason other than the code was written before the implementation of the new syntax. I could be wrong.  @gilbert ?

**Comment by gilbert** [comment]
That's right, `|.` was simply the syntax at the time of writting. I'd be ok with a PR to update it to arrow.
