### ISSUE TITLE
Shouldn’t mapOk operator be `>>|`

### ISSUE THREAD

**Issue by hoichi** [RationalJS/future#35]
I’m not an FP expert, so sorry if I’m mixing something up, but I think convention in OCaml is [to use `>>|` for mappables](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/List/Monad_infix/index.html), not `<$>`.

**Comment by briangorman** [comment]
Looks like Base decided to use a different infix operator. I can see why this would cause confusion, but given that the this library has already implemented an infix operator for map (haskell style), I do not think it is worth it to break backwards compatibility for something relatively minor like this. If this is bothering you a lot, you can define your own implementation of ```>>|```. I think this is something we could revisit if there is ever a third major version of this library.
