### ISSUE TITLE
futurify - Js.Promise interop

### ISSUE THREAD

**Issue by scull7** [RationalJS/future#4]
Here is the function that I'm using for Js.Promise conversion:

```reason
  let futurify = (promise, exn) =>
    Future.make((callback) =>
      promise
      |> Js.Promise.then_(res =>
        Ok(res)
        |> callback
        |> ignore
        |> Js.Promise.resolve
      )
      |> Js.Promise.catch(error=>
        Js.String.make(error)
        |> exn
        |> (err => Error(err))
        |> callback
        |> ignore
        |> Js.Promise.resolve
      )
    );
```
Perhaps this may be useful?

**Comment by gilbert** [comment]
Yes, this is a great reference, thank you.

Do you have any ideas on how to differentiate between different errors? For example, imagine a postgres query potentially throwing a `NoSuchColumn` error or a `NotUnique` error. In normal JS one could write `if err instanceof NotUnique)`. I'm wondering if that's possible to translate to reason (I haven't given much thought to it yet).

**Comment by scull7** [comment]
The `exn` function parameter pushes this responsibility to the caller.  They are free to implement whatever scheme they like

**Comment by gilbert** [comment]
That's true, and is probably the best way to do it 👍

**Comment by scull7** [comment]
Shall I make a PR?

**Comment by gilbert** [comment]
Yes please :) Put it in a new file `FutureJs.re` and name it `fromPromise`. I'd like to keep JS-specific code in its own module, if that makes sense.

**Comment by scull7** [comment]
I've added the `FutureJs.fromPromise` method and associated tests.
