### ISSUE TITLE
Feature Request: Interface files

### ISSUE THREAD

**Issue by seprich** [RationalJS/future#40]
Hi, this library does not for some reason declare interfaces (.rei files). Is this intentional and what would you think of introducing rei-files complete with function signatures? In my opinion it would make easier to understand the library usage if it contains type declarations in addition to implementation. Also type inference is great but when debugging it is helpful if the inference chain does not go inside the library ; either the function usage fits with its environment or not, based on the interface. What do you think?

**Comment by scull7** [comment]
I would think that interface files would always be a welcome addition.
